theme: jekyll-theme-cayman

title: Simple Reeducks 🦆🦆

showcase: True

desc: >-
  An unceremonious, minimalist, and idiomatic Redux port

images:
  - https://raw.githubusercontent.com/ms-jpq/simple-reeducks/master/preview/duck2.jpg
